services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 src.config.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A src worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A src/modules/services beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    # restart: always
    # command: ["/bin/sh", "-c", "until nc -z web 8000; do echo waiting for web; sleep 5; done; nginx -g 'daemon off;'"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge